### ISSUE TITLE
How to configure KUR8 to my own hosted prometheus

### ISSUE THREAD

**Issue by pio2pio** [oslabs-beta/KUR8#149]
I have deployed KUR8 v1.0.0 to EKS v1.18 into `monitoring` namespace but the application was misbehaving. What is I don't know is how to point KUR8 to my prometheus service `kube-prometheus-stack-prometheus:9090`?

The app logs
```log
ur8-depl-7c8f78b546-w88bk kur8 
kur8-depl-7c8f78b546-w88bk kur8 > kur8@0.0.0 dev
kur8-depl-7c8f78b546-w88bk kur8 > concurrently "cross-env NODE_ENV=development webpack serve --hot --open" "cross-env NODE_ENV=development nodemon ./server/index.js"
kur8-depl-7c8f78b546-w88bk kur8 
kur8-depl-7c8f78b546-w88bk kur8 [1] [nodemon] 2.0.12
kur8-depl-7c8f78b546-w88bk kur8 [1] [nodemon] to restart at any time, enter `rs`
kur8-depl-7c8f78b546-w88bk kur8 [1] [nodemon] watching path(s): *.*
kur8-depl-7c8f78b546-w88bk kur8 [1] [nodemon] watching extensions: js,mjs,json
kur8-depl-7c8f78b546-w88bk kur8 [1] [nodemon] starting `node ./server/index.js`
kur8-depl-7c8f78b546-w88bk kur8 [1] jj
kur8-depl-7c8f78b546-w88bk kur8 [1] Listening on port: 3000
kur8-depl-7c8f78b546-w88bk kur8 [0] ℹ ｢wds｣: Project is running at http://localhost:3068/
kur8-depl-7c8f78b546-w88bk kur8 [0] ℹ ｢wds｣: webpack output is served from /build/
kur8-depl-7c8f78b546-w88bk kur8 [0] ℹ ｢wds｣: Content not from webpack is served from /app/client/public
kur8-depl-7c8f78b546-w88bk kur8 [0] ℹ ｢wdm｣: asset bundle.js 4.85 MiB [emitted] (name: main)
kur8-depl-7c8f78b546-w88bk kur8 [0] asset index.html 233 bytes [emitted]
kur8-depl-7c8f78b546-w88bk kur8 [0] orphan modules 441 KiB [orphan] 279 modules
kur8-depl-7c8f78b546-w88bk kur8 [0] runtime modules 29.9 KiB 15 modules
kur8-depl-7c8f78b546-w88bk kur8 [0] modules by path ./node_modules/ 3.59 MiB
kur8-depl-7c8f78b546-w88bk kur8 [0]   cacheable modules 3.58 MiB 689 modules
kur8-depl-7c8f78b546-w88bk kur8 [0]   ./node_modules/webpack/hot/ sync nonrecursive ^\.\/log$ 170 bytes [built] [code generated]
kur8-depl-7c8f78b546-w88bk kur8 [0]   ./node_modules/moment/locale/ sync ^\.\/.*$ 3.21 KiB [optional] [built] [code generated]
kur8-depl-7c8f78b546-w88bk kur8 [0] modules by path ./client/src/ 241 KiB
kur8-depl-7c8f78b546-w88bk kur8 [0]   modules by path ./client/src/components/ 158 KiB 23 modules
kur8-depl-7c8f78b546-w88bk kur8 [0]   modules by path ./client/src/pages/ 33.2 KiB
kur8-depl-7c8f78b546-w88bk kur8 [0]     modules by path ./client/src/pages/AlertsPage/*.js 14.4 KiB 2 modules
kur8-depl-7c8f78b546-w88bk kur8 [0]     modules by path ./client/src/pages/GetStartedPage/*.js 10.5 KiB 2 modules
kur8-depl-7c8f78b546-w88bk kur8 [0]   modules by path ./client/src/reducers/*.js 29.8 KiB 7 modules
kur8-depl-7c8f78b546-w88bk kur8 [0]   modules by path ./client/src/actions/*.js 14.4 KiB 4 modules
kur8-depl-7c8f78b546-w88bk kur8 [0]   modules by path ./client/src/*.js 5.79 KiB 3 modules
kur8-depl-7c8f78b546-w88bk kur8 [0] webpack 5.47.1 compiled successfully in 10938 ms
kur8-depl-7c8f78b546-w88bk kur8 [0] ℹ ｢wdm｣: Compiled successfully.
kur8-depl-7c8f78b546-w88bk kur8 [1] (node:61) [DEP0152] DeprecationWarning: Custom PerformanceEntry accessors are deprecated. Please use the detail property.
kur8-depl-7c8f78b546-w88bk kur8 [1] (Use `node --trace-deprecation ...` to show where the warning was created)
kur8-depl-7c8f78b546-w88bk kur8 [1] Wed, 11 Aug 2021 08:00:59 GMT express deprecated res.send(status, body): Use res.status(status).send(body) instead at file:/app/server/index.js:47:23
kur8-depl-7c8f78b546-w88bk kur8 [1] node:internal/errors:464
kur8-depl-7c8f78b546-w88bk kur8 [1]     ErrorCaptureStackTrace(err);
kur8-depl-7c8f78b546-w88bk kur8 [1]     ^
kur8-depl-7c8f78b546-w88bk kur8 [1] 
kur8-depl-7c8f78b546-w88bk kur8 [1] RangeError [ERR_HTTP_INVALID_STATUS_CODE]: Invalid status code: error found in get request to /podList
kur8-depl-7c8f78b546-w88bk kur8 [1]     at new NodeError (node:internal/errors:371:5)
kur8-depl-7c8f78b546-w88bk kur8 [1]     at ServerResponse.writeHead (node:_http_server:275:11)
kur8-depl-7c8f78b546-w88bk kur8 [1]     at ServerResponse._implicitHeader (node:_http_server:266:8)
kur8-depl-7c8f78b546-w88bk kur8 [1]     at write_ (node:_http_outgoing:763:9)
kur8-depl-7c8f78b546-w88bk kur8 [1]     at ServerResponse.end (node:_http_outgoing:852:5)
kur8-depl-7c8f78b546-w88bk kur8 [1]     at ServerResponse.send (/app/node_modules/express/lib/response.js:221:10)
kur8-depl-7c8f78b546-w88bk kur8 [1]     at ServerResponse.json (/app/node_modules/express/lib/response.js:267:15)
kur8-depl-7c8f78b546-w88bk kur8 [1]     at ServerResponse.send (/app/node_modules/express/lib/response.js:158:21)
kur8-depl-7c8f78b546-w88bk kur8 [1]     at file:///app/server/index.js:47:23
kur8-depl-7c8f78b546-w88bk kur8 [1]     at processTicksAndRejections (node:internal/process/task_queues:96:5) {
kur8-depl-7c8f78b546-w88bk kur8 [1]   code: 'ERR_HTTP_INVALID_STATUS_CODE'
kur8-depl-7c8f78b546-w88bk kur8 [1] }
kur8-depl-7c8f78b546-w88bk kur8 [1] [nodemon] app crashed - waiting for file changes before starting...
kur8-depl-7c8f78b546-w88bk kur8 [0] [HPM] Error occurred while trying to proxy request /podList from localhost:3068 to http://localhost:3000 (ECONNRESET) (https://nodejs.org/api/errors.html#errors_common_system_errors)
kur8-depl-7c8f78b546-w88bk kur8 [0] [HPM] Error occurred while trying to proxy request /deploymentList from localhost:3068 to http://localhost:3000 (ECONNREFUSED) (https://nodejs.org/api/errors.html#errors_common_system_errors)
kur8-depl-7c8f78b546-w88bk kur8 [0] [HPM] Error occurred while trying to proxy request /nodeList from localhost:3068 to http://localhost:3000 (ECONNREFUSED) (https://nodejs.org/api/errors.html#errors_common_system_errors)
```

**Comment by jimmycngo** [comment]
@pio2pio sorry for getting back to you so late. It seems like the proxy to the server isn't starting up properly. We have also included an ingress config yaml file that you can try. 

Try running from the root directory:
```
kubectl -n monitoring apply -f kur8-ingress-srv.yaml
```

Let me know if this works for you. This should connect the kur8's front end to it sever within your cluster.

**Comment by mrmartan** [comment]
I tried to apply the ingress. Does not seem to help.
```
> kur8@0.0.0 dev
> concurrently "cross-env NODE_ENV=development webpack serve --hot --open" "cross-env NODE_ENV=development nodemon ./server/index.js"
[1] [33m[nodemon] 2.0.12[39m
[1] [33m[nodemon] to restart at any time, enter `rs`[39m
[1] [33m[nodemon] watching path(s): *.*[39m
[1] [33m[nodemon] watching extensions: js,mjs,json[39m
[1] [32m[nodemon] starting `node ./server/index.js`[39m
[1] jj
[1] Listening on port: 3000
[0] [34mℹ[39m [90m｢wds｣[39m: Project is running at http://localhost:3068/
[0] [34mℹ[39m [90m｢wds｣[39m: webpack output is served from /build/
[0] [34mℹ[39m [90m｢wds｣[39m: Content not from webpack is served from /app/client/public
[1] (node:62) [DEP0152] DeprecationWarning: Custom PerformanceEntry accessors are deprecated. Please use the detail property.
[1] (Use `node --trace-deprecation ...` to show where the warning was created)
[0] [34mℹ[39m [90m｢wdm｣[39m: asset bundle.js 4.85 MiB [emitted] (name: main)
[0] asset index.html 233 bytes [emitted]
[0] orphan modules 441 KiB [orphan] 279 modules
[0] runtime modules 29.9 KiB 15 modules
[0] modules by path ./node_modules/ 3.59 MiB
[0] cacheable modules 3.58 MiB 689 modules
[0] ./node_modules/webpack/hot/ sync nonrecursive ^\.\/log$ 170 bytes [built] [code generated]
[0] ./node_modules/moment/locale/ sync ^\.\/.*$ 3.21 KiB [optional] [built] [code generated]
[0] modules by path ./client/src/ 241 KiB
[0] modules by path ./client/src/components/ 158 KiB 23 modules
[0] modules by path ./client/src/pages/ 33.2 KiB
[0] modules by path ./client/src/pages/AlertsPage/*.js 14.4 KiB 2 modules
[0] modules by path ./client/src/pages/GetStartedPage/*.js 10.5 KiB 2 modules
[0] modules by path ./client/src/reducers/*.js 29.8 KiB 7 modules
[0] modules by path ./client/src/actions/*.js 14.4 KiB 4 modules
[0] modules by path ./client/src/*.js 5.79 KiB 3 modules
[0] webpack 5.47.1 compiled successfully in 11508 ms
[0] [34mℹ[39m [90m｢wdm｣[39m: Compiled successfully.
[1] Wed, 24 Nov 2021 16:10:58 GMT express deprecated res.send(status, body): Use res.status(status).send(body) instead at file:/app/server/index.js:47:23
[1] node:internal/errors:464
[1] ErrorCaptureStackTrace(err);
[1] ^
[1]
[1] RangeError [ERR_HTTP_INVALID_STATUS_CODE]: Invalid status code: error found in get request to /podList
[1] at new NodeError (node:internal/errors:371:5)
[1] at ServerResponse.writeHead (node:_http_server:275:11)
[1] at ServerResponse._implicitHeader (node:_http_server:266:8)
[1] at write_ (node:_http_outgoing:763:9)
[1] at ServerResponse.end (node:_http_outgoing:852:5)
[1] at ServerResponse.send (/app/node_modules/express/lib/response.js:221:10)
[1] at ServerResponse.json (/app/node_modules/express/lib/response.js:267:15)
[1] at ServerResponse.send (/app/node_modules/express/lib/response.js:158:21)
[1] at file:///app/server/index.js:47:23
[1] at processTicksAndRejections (node:internal/process/task_queues:96:5) {
[1] code: 'ERR_HTTP_INVALID_STATUS_CODE'
[1] }
[0] [HPM] Error occurred while trying to proxy request /podList from localhost:3068 to http://localhost:3000 (ECONNRESET) (https://nodejs.org/api/errors.html#errors_common_system_errors)
[1] [31m[nodemon] app crashed - waiting for file changes before starting...[39m
[0] [HPM] Error occurred while trying to proxy request /serviceList from localhost:3068 to http://localhost:3000 (ECONNRESET) (https://nodejs.org/api/errors.html#errors_common_system_errors)
[0] [HPM] Error occurred while trying to proxy request /deploymentList from localhost:3068 to http://localhost:3000 (ECONNRESET) (https://nodejs.org/api/errors.html#errors_common_system_errors)
[0] [HPM] Error occurred while trying to proxy request /ingressList from localhost:3068 to http://localhost:3000 (ECONNRESET) (https://nodejs.org/api/errors.html#errors_common_system_errors)
[0] [HPM] Error occurred while trying to proxy request /nodeList from localhost:3068 to http://localhost:3000 (ECONNRESET) (https://nodejs.org/api/errors.html#errors_common_system_errors)
```
